# Sync repo to the Codeberg mirror
# based on the example script https://github.com/Tuxilio/sync-test/blob/main/.github/workflows/codeberg-mirror.yml
name: Repo sync GitHub -> Codeberg
on:
  push:
    branches:
    - '**'

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: spyoungtech/mirror-action@v0.7.0
        with:
          REMOTE: "https://codeberg.org/Tuxilio/sync-test.git"
          GIT_USERNAME: iksbi-penguin-bot
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
